server:
  port: 8080
  address: localhost
spring:
  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true

  datasource:
    name: chocolate
    url: jdbc:mysql://localhost:3306/chocolate?useUnicode=true&amp;charaterEncoding=utf-8
    username: root
    password: root
    # druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    connectionTestQuery: SELECT 1
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    driver-class-name: com.mysql.jdbc.Driver
    #schema: classpath:init-sql/schema.sql
    continueOnError: true
    resources.static-locations: classpath:/resources/,classpath:/static/

  jpa:
    hibernate:
      ddl-auto: update

  thymeleaf:
    check-template-location: false
    cache: false

logging:
  level:
    org.springframework:
      web: INFO
